### ISSUE TITLE
Follow up from .NET nanoFramework

### ISSUE THREAD

**Issue by josesimoes** [michaelschwarz/NETMF-Toolkit#2]
Hi Michael,

Don't know if you are aware of .NET [nanoFramework](https://github.com/nanoframework). 
We would like to "take" pieces of your wonderful NETMF-toolkit and port it to nanoFramework.

Wanted to check with your first if that's OK with you.

Thanks!

CC @piwi1263 @RoSchmiSec

**Comment by michaelschwarz** [comment]
Hi Jose,

definitely I am happy taking parts of my sources, that's how we can work together.

Regards, Michael
